version: "3.6"
services:
  gdu-bot:
    build: ./
    volumes:
      - ./data/:/app/data/
    env_file: .env
    ports:
      - ${API_PORT}:${API_PORT}
      - "9229:9229"
    command:
      - node
      - "--inspect-brk=0.0.0.0"
      - "./dist"