version: "3.6"
services:
  gdu-bot:
    build: ./
    volumes:
      - ./data/:/app/data/
    env_file: .env
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - gdu
networks:
  gdu:
    external: true
